name: studenttool
description: Flutter application for student life organization. A lot of functionality included.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bottom_navy_bar: ^5.4.0
  cupertino_icons: ^0.1.3
  pedantic: ^1.8.0
  google_fonts: ^1.1.0
  provider: ^4.1.2
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

